# Generated by Django 5.0.6 on 2024-06-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='license_plate',
            new_name='plate',
        ),
    ]
